packages/alpine/src/index.ts

Just trying to start this unreleased Alpine plugin on my TALL project, but it logged a message on the console. I assume this is just a `console.log` for debugging purpose and shouldn't be there, so I'm proposing to delete it.

Remove `console.log` call

---

packages/react-inertia/package.json
packages/react-inertia/src/index.ts

We are currently re-binding the event listener on each render. Leaning on a "booted" ref to determine if it's the first render.

[0.1.x] Ensure event listener is only bound once

---

packages/react-inertia/src/index.ts
packages/vue-inertia/src/index.ts

Couple of places where we aren't converting uppercase methods, e.g., `POST`, to the expected lowercase version.

[0.1.x] Standardise support for uppercase method

---

packages/alpine/package.json
packages/react-inertia/package.json
packages/react-inertia/src/index.ts
packages/react/package.json
packages/vue-inertia/package.json
packages/vue-inertia/src/index.ts
packages/vue/package.json

This fixes an issue in React w/ Inertia where the `processing` property was not responding correctly.
Although the issue isn't present in the Vue version due to the different way that Vue works under the hood, for consistency we are also removing the monkey-patched property from the Vue w/ Inertia package and relying property already provided by Inertia.
fixes #12
I've also had to update the version constraint, as it is currently broken after the latest release.

[0.3.x] Use Inertia's processing property

---

RELEASE.md
bin/release
packages/alpine/package.json
packages/react-inertia/package.json
packages/react/package.json
packages/vue-inertia/package.json
packages/vue/package.json

- Ensure that explicit versions are used - rather than a range constraint.
- Introduce an executable `bin/release` script that will assist with bumping dependency version of the subpackages and versioning them at the same time.
We need this script because as the subpackages depend on each other. For example, the `precog-vue` package depends on the "core" package. When we version the vue package we need to bump the core version in the dependency list of the vue package.
Unfortunately, `npm` does not currently respect the order of the workspaces `"packages"` when versioning, so we cannot use the native `preversion` / `version` hooks to perform this work.
The script currently only does the work we would previously do when running `npm version patch`. We still need to manually publish. The …

[0.3.x] Improve versioning

---

packages/alpine/src/index.ts
packages/core/src/client.ts
packages/core/src/types.ts
packages/core/src/validator.ts
packages/core/tests/validator.test.js
packages/react/src/index.ts
packages/vue/src/index.ts

Fields that have been "touched" are marked as "valid" when a validation request is in flight, if they have not yet been validated.
This fixes that issue and ensures that we only mark fields as valid once the response has returned and is:
1. Successful: 200 -> 299 status
2. Validation error: 422
Fixes https://github.com/laravel/precognition/issues/18

[0.3.x] Ensure marked as valid once response returns

---

packages/alpine/src/index.ts
packages/core/src/client.ts
packages/core/src/index.ts
packages/core/tests/client.test.js
packages/core/tests/validator.test.js
packages/react-inertia/src/index.ts
packages/react/src/index.ts
packages/vue-inertia/src/index.ts
packages/vue/src/index.ts

This PR allows configuration values to override (or merge with) the initial data provided when creating the validator. This is useful for validation if you wish to change these values just for the "submission" of the form itself, via `form.submit(OPTIONS)`
Also, it also allows the url and method to be specified as a callback, which allows the them to be changed after the form as been created...
```js
let endpoint = null;
form = useForm('post', () => endpoint, {});
endpoint = 'https://first.com';
form.validate('name');
endpoint = 'https://second.com';
form.validate('name');
```
This can be useful if your form url is dynamic and determined by the current state of the application.
Fixes https://github.com/laravel/precognition/issues/20

[0.3.x] Allow config to override initial values

---

packages/alpine/src/index.ts
packages/core/src/client.ts
packages/core/src/types.ts
packages/core/tests/client.test.js
packages/core/tests/validator.test.js
packages/react-inertia/src/index.ts
packages/react/src/index.ts
packages/vue-inertia/src/index.ts
packages/vue/src/index.ts

This PR exposes the axios client across all libraries to enable easy configuration of all precognition request.
```js
import { client } from 'laravel-precognition-LIBRARY'
client.axios().defaults.headers.common['Authorization'] = AUTH_TOKEN;
```
fixes #21
It is already possible to pass a pre-configured axios instance.
```js
import { client } from 'laravel-precognition-LIBRARY'
// ...
client.use(myAxiosInstace)
```

[0.3.x] Expose the client / axios instance

---

packages/core/src/client.ts
packages/core/src/validator.ts
packages/react-inertia/src/index.ts
packages/react/src/index.ts
packages/vue-inertia/src/index.ts
packages/vue/src/index.ts

It seems that we cannot use the `setError` method of laravel-precognition-react-inertia in the current implementation.
Upon inspecting the internals, it appears that the `setError` method uses `setErrors` internally.
However, due to a mistake with `this` variable, attempting to use `setError` was resulting in it being interpreted as a non-existent property and couldn't be used. 
I have made the necessary corrections to address this issue, so `setError` should now be properly usable.

[0.3.x] Fix react-inertia setError bug

---

packages/alpine/src/index.ts
packages/alpine/src/types.ts
packages/core/src/types.ts
packages/core/src/validator.ts
packages/core/tests/client.test.js
packages/core/tests/validator.test.js
packages/react-inertia/src/index.ts
packages/react/src/index.ts
packages/react/src/types.ts
packages/vue-inertia/src/index.ts
packages/vue/src/index.ts
packages/vue/src/types.ts

This PR allows developers to manually "touch" inputs and also invoke the "validate" method without specifying a specific input to validate.
This can be useful for multi-step forms where the form is not being submitted at the end of the page, but all field should be validated.
Because Precognition only validates "touched" inputs, which are inputs that have had the `validate` function called on them, it is not currently possible to support this kind of validation behaviour.
With this PR, it is now possible to do the following at the end of a step of a multi-step form...
```js
form.touch([
'name',
'email',
'username',
'phone',
'address',
]).validate()
```
This will send a validation request for all the already "touched" fields and include the specified touch fields as well.
This can also be …

[0.3.x] Allow fields to be manually touched

---

packages/core/src/client.ts
packages/core/tests/client.test.js

🚨 Breaking change. Requires a major version bump, i.e., `0.5.x`.
[We introduced a new header](https://github.com/laravel/framework/pull/47081) to determine if Precognition was truly successful.
To ease migration and not impact existing applications using Precognition that had not yet updated to [v10.11.0 (2023-05-16)](https://github.com/laravel/framework/blob/10.x/CHANGELOG.md#v10110-2023-05-16), I intentionally delayed adding it to our JS package.
With the introduction of the [testing helpers](https://github.com/laravel/framework/pull/48151), I felt this was a good time to make this breaking change and bring everything inline.
This is now a required header for responses, meaning that when this new version is tagged - consuming Laravel applications will need to update to `^10.11.0`.
For …

[0.5.x] [BREAKING] Require `Precognition-Success` header

---

packages/alpine/src/index.ts

When using Alpine, you are able to use Precognition's client to do form submissions. When doing submissions with Precognition's client the `processing` flag is updated as expected, however when doing traditional browser submissions it isn't. This was a limitation I accepted, however I realised we can just bind an event listener to the DOM form's `submit` event and we can get feature parity for both implementations.
Now both of these examples will have the button disabled when the form is submitted.
```html
<form
x-data="{
form: $form('post', '/register', {
name: '',
}),
}"
>
@csrf
<label for="name">Name</label>
<input
id="name"
name="name"
x-model="form.name"
@change="form.validate('name')"
/>
<template x-if="form.invalid('name')">
<div x-text="form.errors.name"></div>
</template>
<label …
```

[0.5.x] Update `processing` flag for traditional for submissions

---

packages/vue-inertia/package.json
packages/vue-inertia/src/index.ts

Fixes https://github.com/laravel/precognition/issues/48
When we destructure the Precognitive form, e.g.,
```js
inertiaForm.validating = precognitiveForm.validating
```
the reactivity for `validating` is not inherited. This is due to the way that Vue handles destructing `reactive` properties. 
We now watch for changes and apply them manually.

[0.5.x] Fixes Vue w/ Inertia validating reactivity

---

packages/alpine/src/index.ts
packages/core/src/validator.ts
packages/core/tests/validator.test.js
packages/react/src/index.ts
packages/vue/src/index.ts

fixes https://github.com/laravel/precognition/issues/58
It is possible for Precognition to get out of sync with what inputs are reported as being "valid".
This fixes the issue by:
1. Delaying listeners until all state has been updated.
2. Making sure the library specific implementations update their "valid" state when errors change.
Note: The reported "invalid" inputs are _always_ correct and not impacted by this bug.

[0.8.x] Fix incorrectly reported valid inputs

---

packages/alpine/package.json
packages/alpine/src/index.ts
packages/core/package.json
packages/core/src/client.ts
packages/core/src/validator.ts
packages/react/package.json
packages/react/src/index.ts
packages/vue/package.json
packages/vue/src/index.ts

This pull request represents a significant enhancement to our project's dependency management and security posture. We are transitioning from using individual lodash packages to the unified lodash package. This change is motivated by two primary factors: the discontinuation of maintenance for individual lodash modules and a critical security vulnerability in lodash.set.
Key changes:
- Unified Lodash Package: All individual lodash packages (lodash.*) are replaced with the single, comprehensive lodash package. This consolidation simplifies dependency management and ensures we are using the most up-to-date and supported version of lodash.
- Security lodash.set: The individual lodash.set package currently utilized in our project has a known prototype pollution vulnerability (CWE-1321). By …

[0.5.x] Migrate to lodash-es

---

packages/react-inertia/src/index.ts
packages/vue-inertia/src/index.ts
packages/vue-inertia/tests/index.test.ts

Fixes https://github.com/laravel/precognition/issues/70
Adds support for Inertia's transform function.
```js
const form = useForm('post', '/register', {
emails: ''
}).transform(data => ({
...data,
emails: data.emails.split(',').map(email => email.trim()),
})
form.emails = 'tim@laravel.com, taylor@laravel.com'
form.validate('emails') // { emails: ['tim@laravel.com', 'taylor@laravel.com'] }
form.submit()           // { emails: ['tim@laravel.com', 'taylor@laravel.com'] }
```

Support Inertia `transform`

---

packages/core/src/client.ts
packages/core/tests/validator.test.js

fixes https://github.com/laravel/precognition/issues/73
The precognition client will always cancel in-flight requests that match a new outgoing request. This is done to ensure that only the latest validation messages are returned and that we don't get out-of-order responses.
For non-Inertia libraries, we also use the client to submit forms. There are rare situations where a validation request can cancel and actual submission request.
This PR ensures that non-precognitive requests are never cancelled by the library - which is the expected behaviour.
This only impacts the non-Inertia flavoured libraries.

[1.x] Ensures precog requests do not interfere with non-precog requests

---

packages/vue/src/index.ts

Vue has improved their type system and these ignore comments are no longer valid. Having them in place is breaking the build.

[1.x] Removes unused ignore comments

---

package.json
packages/alpine/package.json
packages/alpine/src/index.ts
packages/alpine/src/types.ts
packages/core/package.json
packages/core/src/types.ts
packages/core/src/validator.ts
packages/core/tests/client.test.js
packages/core/tests/validator.test.js
packages/react-inertia/package.json
packages/react-inertia/src/index.ts
packages/react/package.json
packages/react/src/index.ts
packages/react/src/types.ts
packages/vue-inertia/package.json
packages/vue-inertia/src/index.ts
packages/vue/package.json
packages/vue/src/index.ts
packages/vue/src/types.ts

This PR introduces the ability to respond to individual validation requests via a callback. 
This is the most requested feature of Precognition.
- https://github.com/laravel/precognition/issues/59
- https://github.com/laravel/precognition/issues/56
- https://github.com/laravel/precognition/issues/51
- https://github.com/laravel/precognition/issues/83
- https://github.com/laravel/precognition/issues/47
- https://github.com/laravel/precognition/pull/66
- https://github.com/laravel/precognition/pull/67
The validate method now accepts a second parameter that can accept configuration.
```vue
<TextInput
v-model="form.name"
@change="form.validate('name', {
onSuccess: () => /* ... */,
onValidationError: () => /* .. */,
})"
/>
```
This is also useful when building a wizard. You may call `validate` …

[1.x] Async validate

---

packages/vue-inertia/src/index.ts
packages/vue-inertia/src/types.ts
packages/vue/src/types.ts

The `useForm` composable for Inertia has no types.
This PR adds them.

[0.5.x] Type `vue-inertia`

---

package.json

Small quality of life improvement while developing and running `npm run watch` across all packages.
Previously was using bash background jobs.

[0.5.x] Use `npx concurrently` for `npm run watch` command

---

packages/react-inertia/src/index.ts
packages/vue-inertia/src/index.ts

fixes https://github.com/laravel/precognition/issues/101
There is a console error written when a submission is done with the Inertia ordered parameters.
This is because we are incorrectly assuming there is a third parameter, which is actually optional.
We now check that the third parameter is defined.

[0.5.x] Handle missing `onError` callback

---

packages/alpine/package.json
packages/core/package.json
packages/core/src/validator.ts
packages/core/tests/validator.test.js
packages/react-inertia/package.json
packages/react/package.json
packages/vue-inertia/package.json
packages/vue/package.json

Precognition does its best to avoid sending requests when it does not need to. This might happen when the validation function has been called but the form's has not changed since the last validation attempt.
You could imagine a text input where the user changes a value and before leaving the field restores the original value. In that scenario there is no need to send a validation request as the form has not changed and the existing validation errors etc still makes sense.
This is the expected behaviour when you are validating a single field and the user is implicitly invoking the `validate` function.
```vue
<input
v-model="form.email"
@change="form.validate('name')"
>
```
However, when building a wizard and calling `form.validate()` in a button without specifying a particular input to …

[0.5.x] Re-work on-change validation

---

packages/alpine/src/index.ts

When using the Alpine library, it is common to continue using native browser form submissions.
A common pattern is to disable inputs on submit via a `fieldset` group.
```html
<form
x-data="{
form: $form('post', '/register', {
name: ''
}),
}"
>
<fieldset
x-bind:disabled="form.processing"
>
<input
name="name"
x-model="form.name"
@change="form.validate('name')"
>
</fieldset>
<button>Submit</button>
</form>
```
When we detect a native browser submission, via the `formElement.addEventListener('submit')` listener, we set `processing = true`, however because the event listener triggers before the browser has actually sent the request it disables the inputs BEFORE the submission and the form inputs are not sent to the browser.
Browsers do not submit disabled inputs.
Source: …

[0.5.x] Improve native browser submission while disabling formset on submit

---

packages/core/src/client.ts
packages/core/src/types.ts
packages/core/src/validator.ts
packages/core/tests/client.test.js
packages/core/tests/validator.test.js

The API when working with a form wizard is less than ideal. We have done a lot of work recently to make this experience better, but the API never felt right.
You currently need to call the `touch` method to ensure the current page's inputs are validated. Inputs are marked as touch when a user interacts with them, but in a wizard you need to validate chunks of the form at a time even if the user has not interacted with the inputs.
```jsx
<button
onClick={() => form.touch(['name', 'email']).validate({
onSuccess: () => nextStep(),
})}
>
Next Step
</button>
```
It is also not possible to un-touch an input, which can cause issues with certain form wizard configurations where you hide old inputs.
This PR intends to make the wizard API better while addressing the issue with not being able to …

[0.5.x] Improve async validation API

---

packages/react-inertia/src/index.ts
packages/react-inertia/src/types.ts
packages/vue-inertia/src/index.ts
packages/vue-inertia/src/types.ts

Some recent type narrowing in Inertia(https://github.com/inertiajs/inertia/commit/8bc7fc45173f0504c5b7756af8153e01a6fedd84) has caused build issues here.
This fixes those issues. We are duplicating the Inertia type until we drop Inertia 1 support.

Fix Inertia types

---

packages/vue-inertia/src/index.ts
packages/vue-inertia/tests/index.test.ts
packages/vue/src/index.ts

This PR adds support for inputs data getter in vue and vue-inertia Forms. 
It's mirroring the functionality of `@inertiajs/vue3`'s `useForm`.
```ts
let dynamicEmail = 'taylor@laravel.com'
function getData() {
return { email: dynamicEmail }
}
const form = useForm('post', '/register', getData) 
```

[0.6.x]: Data Getter Support in vue and vue-inertia Forms

---

packages/react-inertia/src/index.ts
packages/react-inertia/src/types.ts

The React Inertia useForm() hook is typed to return `any`, but we can improve this by returning `Form<Data>`, similar to the React Vue plugin.
However, there's no types.ts file in the `react-inertia` package, though the file exists in the `vue-inertia` package.
https://github.com/laravel/precognition/tree/main/packages/react-inertia/src
https://github.com/laravel/precognition/tree/main/packages/vue-inertia/src
I copied the types.ts file from vue-inertia, modified it with the correct imports, and updated the useForm() return type.

[0.6.x] Typescript return type for React Inertia useForm()

---

packages/alpine/src/index.ts
packages/react-inertia/src/index.ts
packages/react/src/index.ts
packages/vue-inertia/src/index.ts
packages/vue/src/index.ts

It would be helpful if we could import the Form type so we can do things like this:
```ts
import {PrecognitionForm, useForm} from "laravel-precognition-react-inertia";
type MyForm = {
name: string;
};
type ContextType = {
form: PrecognitionForm<MyForm>;
};
const Context = createContext({} as ContextType);
function SomeComplextForm() {
const form = useForm<MyForm>("post", route("users.store"), user);
return <Context.Provider value={{form}}>...</Context.Provider>;
}
```
This pull request exports `Form` as `PrecognitionForm`.

[0.7.x] Export the Form type
